### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by aka-deVOID** [FyroxEngine/Fyrox#466]
I have a compile error

error detail:

```
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5181:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5181:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5181:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5704:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM default
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("\"No such file or directory\"")', /home/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fyroxed_base-0.17.0/src/lib.rs:498:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

I install all library and all of them exist.

**Comment by mrDIMAS** [comment]
> I install all library and all of them exist.

All of these - https://fyrox-book.github.io/fyrox/beginning/scripting.html#linux ? Make sure that you have `libasound2-dev` installed.

**Comment by aka-deVOID** [comment]
yes im on Arch linux
alsa-lib installed

**Comment by mrDIMAS** [comment]
Hm, looking at the output again this does not look like a _compile_ error, it looks like _runtime_ error. It looks like it cannot find a sound card or something similar.

**Comment by aka-deVOID** [comment]
yes, I made a mistake it's a runtime error my sound card working fine now.
```
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("\"Device or resource busy\"")', /home/devoid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fyroxed_base-0.17.0/src/lib.rs:498:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I reinstall alsa-lib but now I have this.

**Comment by aka-deVOID** [comment]
you can fix with this: https://forums.debian.net/viewtopic.php?t=123902
