### ISSUE TITLE
apk crashes on load

### ISSUE THREAD

**Issue by codegod100** [FyroxEngine/Fyrox#679]
I can build the apk and install but it crashes when I try to run.

I tried to debug from cli, but my adb-foo is not elite class.

I tried 
```
v@buildbox:~/fyrox_test/build$ /home/v/Android/Sdk/platform-tools/adb -s "<unknown>" shell am start -a android.intent.action.MAIN -n rust.executor_android/android.app.NativeActivity
Starting: Intent { act=android.intent.action.MAIN cmp=rust.executor_android/android.app.NativeActivity }
```

This runs the apk, but it crashes immediately without any output from cli. Maybe someone more advanced can help?

**Comment by codegod100** [comment]
Figured out how to get crash log

```
09-10 22:15:30.416 29829 29829 E AndroidRuntime: FATAL EXCEPTION: main
09-10 22:15:30.416 29829 29829 E AndroidRuntime: Process: rust.executor_android, PID: 29829
09-10 22:15:30.416 29829 29829 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Unable to load native library "/data/app/~~9OgzFcwpo8da9rmzVtRJEQ==/rust.executor_android-v9_nSAxYk_ZI0jBOfI2RMA==/lib/arm/libexecutor_android.so": dlopen failed: library "libstd-04c473f841fcc0b6.so" not found: needed by /data/app/~~9OgzFcwpo8da9rmzVtRJEQ==/rust.executor_android-v9_nSAxYk_ZI0jBOfI2RMA==/lib/arm/libexecutor_android.so in namespace clns-4
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at android.app.NativeActivity.onCreate(NativeActivity.java:178)
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8767)
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8745)
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1519)
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3928)
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4126)
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:108)
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195)
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157)
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90)
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2544)
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8501)
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
09-10 22:15:30.416 29829 29829 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by mrDIMAS** [comment]
Turns out that, when you running the editor in hot-reloading mode, `RUSTFLAGS="-C prefer-dynamic=yes"` are leaking into the child processes forcing any `cargo` calls to use these flags and use dynamic linking. The temporary solution is to use the editor in normal mode (`cargo run --package editor --release`).
